### PR TITLE
Add synthesis

### PR DESCRIPTION
**Pull request by ncharl**
Add synthesis to AIG using `-S filename.aag` or `-S -` to print to stdout.
From the build folder: `meson test --suite synth` runs 11 tests doing synthesis for a TLSF file and model checking acacia-bonsai's output.

### CODE REVIEW

**Comment by gaperez64** [comment]
This should resolve issue #17

**Comment by gaperez64** [comment]
@ncharl does this resolve #22 too?

**Comment by ncharl** [comment]
It does not, I only changed that in the composition branch. I can fix it here as well if you prefer?

**Comment by gaperez64** [comment]
No that's fine, I am currently reviewing the first pull request. Keep it
for the next one.

**Comment by gaperez64** [comment]
@ncharl I fixed the CI for the benchmarks, if you update your fork and it goes through then I'll merge this now :)

**Pull request merged**
